# Generated by Django 3.2.7 on 2021-10-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20211015_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_addresses', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role_is_borrower', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='number_of_copies',
            new_name='number_of_copies_bought',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing_Log',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('borrowing_date', models.CharField(max_length=100)),
                ('returning_date', models.CharField(max_length=100)),
                ('book_returned', models.CharField(max_length=20)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
        ),
    ]
