# Generated by Django 3.2.7 on 2021-11-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_feedback_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing_log',
            name='id',
        ),
        migrations.AddField(
            model_name='borrowing_log',
            name='trans_id',
            field=models.CharField(default='abc', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrowing_log',
            name='book_id',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='apis.book'),
        ),
        migrations.AlterField(
            model_name='borrowing_log',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='apis.user'),
        ),
    ]
