# Generated by Django 3.2.7 on 2021-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20211103_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_copies_bought',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrowing_log',
            name='book_returned',
            field=models.BooleanField(),
        ),
    ]
