# Generated by Django 3.2.7 on 2021-11-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20211103_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing_log',
            name='borrowing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrowing_log',
            name='returning_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrowing_log',
            name='trans_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
