# Generated by Django 3.2.7 on 2021-11-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20211104_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_is_borrower',
            field=models.BooleanField(),
        ),
    ]
