# Generated by Django 3.2.7 on 2021-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_alter_user_role_is_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing_log',
            name='trans_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
